spring.datasource.url=jdbc:mysql://localhost:3306/logitrack_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#le va a decir a spring que tiene que ejecutar data.sql despues de que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true
# OBLIGA a Spring Boot a ejecutar los scripts sql incluso en MySQL
spring.sql.init.mode=always